package model;

/**
 * Created by GligaBogdan on 31-Mar-16.
 */
public enum Type {

    NOT_ENOUGH_MEMORY, MEMORY_FRAGMENTATION, SECURITY, NOT_ENOUGH_MEMORY_SOLLUTION, MEMORY_FRAGMENTATION_SOLLUTION, ACCESS_MEMORY_DETAIL, PAGE_TABLE

}
